INVT-10360 extend deployment test to main.js

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -63,11 +63,20 @@ jobs:
           expectedIndexHtml="<h1>Hello World!</h1>"
           indexHtmlUrl="https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/index.html?$SAS_TOKEN"
           receivedIndexHtml=$(curl -X GET -H "x-ms-date: $(date -u)" "$indexHtmlUrl")
-          echo $receivedIndexHtml
           if [[ $receivedIndexHtml != *"$expectedIndexHtml"* ]]; then
             echo "::error ::Deployment of index.html has not been successful"
+            echo "expected: $expectedIndexHtml but received: $receivedIndexHtml"
             exit 1
           fi
+          expectedMainJs="console.log('Hello World!');"
+          mainJsUrl="https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action/main.js?$SAS_TOKEN"
+          receivedMainJs=$(curl -X GET -H "x-ms-date: $(date -u)" "$mainJsUrl")
+          if [[ $receivedMainJs != *"$expectedMainJs"* ]]; then
+            echo "::error ::Deployment of main.js has not been successful"
+            echo "expected: $expectedMainJs but received: $receivedMainJs"
+            exit 1
+          fi
+
 
       - name: Modify the microfrontend by introducing a breaking change
         run: python ./.github/workflows/introduce_breaking_change.py
