INVT-10360 combine two test workflows and use dir in rollback
The two distinct test workflows broke each other by running in parallel and deploying to the same container.
The rollback mode did not use the sourceDirectory option, thus looked into the wronge directory to find the backup file.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,7 +3,7 @@ on: [push]
 
 jobs:
   test:
-    name: Test Deployment
+    name: Test Deployment and Rollback
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -13,21 +13,13 @@ jobs:
         uses: leanix/secrets-action@master
         with:
           secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}
-      
+
       - name: Extract branch name
         shell: bash
         run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
         id: extract-branch
-
-      - name: Use storage deploy action
-        uses: ./
-        with:
-          branch: ${{ steps.extract-branch.outputs.branch }}
-          source-directory: test
-          container: storage-deploy-action-public
-          environment: test
       
-      - name: Use storage deploy action for deploying a microfrontend
+      - name: Deploy a microfrontend to all regions
         uses: ./
         with:
           branch: ${{ steps.extract-branch.outputs.branch }}
@@ -36,7 +28,7 @@ jobs:
           environment: test
           microfrontend: test-microfrontend
 
-      - name: Use storage deploy action with region option
+      - name: Deploy a microfrontend with region option
         uses: ./
         with:
           branch: ${{ steps.extract-branch.outputs.branch }}
@@ -44,8 +36,74 @@ jobs:
           container: storage-deploy-action-public
           environment: test
           region: westeurope
+          microfrontend: test-microfrontend
+        id: initial-deployment 
 
-      - name: Should fail because of unsupported region
+      - name: Deployment has been successful index.html and main.js
+        shell: bash
+        run: |
+          expected="<h1>Hello World!</h1>console.log('Hello World!');"
+          received=$(curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html && curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js)
+          if [[ $received != *"$expected"* ]]; then
+            echo "::error ::Deployment has not been successful"
+            exit 1
+          fi
+
+      - name: Modify the microfrontend by introducing a breaking change
+        run: python ./.github/workflows/introduce_breaking_change.py
+
+      - name: Deploy new version
+        uses: ./
+        with:
+          branch: ${{ steps.extract-branch.outputs.branch }}
+          source-directory: test
+          container: storage-deploy-action-public
+          environment: test
+          region: westeurope
+          microfrontend: test-microfronted
+        id: breaking-change-deployment
+
+      - name: Deployment of breaking change has been successful 
+        shell: bash
+        run: |
+          expected="<h1>Breaking Change</h1>console.log('Breaking Change');"
+          received=$(curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html && curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js)
+          if [[ $received != *"$expected"* ]]; then
+            echo "::error ::Deployment has not been successful"
+            exit 1
+          fi
+
+      - name: Rollback the breaking change deployment to the initial deployed version
+        uses: ./
+        with:
+          container: storage-deploy-action-public
+          source-directory: test
+          environment: test
+          region: westeurope
+          rollback-mode: true
+          rollback-version: ${{ steps.initial-deployment.outputs.version }}
+
+      - name: Rollback of index.html and main.js has been successful
+        shell: bash
+        run: |
+          expected="<h1>Hello World!</h1>console.log('Hello World!');"
+          received=$(curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html && curl -s https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js)
+          if [[ $received != *"$expected"* ]]; then
+            echo "::error ::Rollback has not been successful"
+            exit 1
+          fi
+
+      - name: Rollback fails, if no rollback-version specified
+        uses: ./
+        continue-on-error: true
+        with:
+          branch: ${{ steps.extract-branch.outputs.branch }}
+          source-directory: test
+          container: storage-deploy-action-public
+          environment: test
+          rollback-mode: true
+      
+      - name: Fails because of unsupported region
         uses: ./
         continue-on-error: true
         with:
@@ -54,8 +112,8 @@ jobs:
           container: storage-deploy-action-public
           environment: test
           region: northeurope
-
-      - name: Should fail because of forbidden container name
+      
+      - name: Fails because of forbidden container name
         uses: ./
         continue-on-error: true
         with:
@@ -63,22 +121,22 @@ jobs:
           source-directory: test
           container: foobar
 
-      - name: Should fail because of not existing container name
+      - name: Fails because of non-existing container name
         uses: ./
         continue-on-error: true
         with:
           branch: ${{ steps.extract-branch.outputs.branch }}
           source-directory: test
           container: storage-deploy-action-unknown
-      
-      - name: Should fail because of missing source directory
+
+      - name: Fails because of missing source directory
         uses: ./
         continue-on-error: true
         with:
           branch: ${{ steps.extract-branch.outputs.branch }}
           container: storage-deploy-action-public
 
-      - name: Should fail because of invalid region
+      - name: Fails because of invalid region
         uses: ./
         continue-on-error: true
         with:
@@ -87,7 +145,7 @@ jobs:
           container: storage-deploy-action-public
           region: foobar
 
-      - name: Should fail because of invalid environment
+    - name: Fails because of invalid environment
         uses: ./
         continue-on-error: true
         with:
@@ -95,8 +153,8 @@ jobs:
           source-directory: test
           container: storage-deploy-action-public
           environment: foobar
-      
-      - name: Should fail because no branch provided
+
+    - name: Fails because no branch provided
         uses: ./
         continue-on-error: true
         with:
