INVT-10721 add optional versioning step
If the user wants to version the current deployment, they can now use three additional input parameters that make this possible.
The deployment strategy calculates a release versioned based on existing release tags in the corresponding deployed branch.
This is the same strategy as previously used to create a versioned Docker container.

The versioning step is completly optional and clients, which do not provide any of the new input parameters will not notice any changes to their pipelines.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,8 +25,29 @@ jobs:
       - name: Define variables
         run: |
           echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/test.txt" > TEST_TXT_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index.html" > INDEX_HTML_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main.js" > MAIN_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/polyfills.js" > POLYFILLS_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/polyfills-es5.js" > POLYFILLS_ES5_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/styles.css" > STYLES_CSS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/scripts.js" > SCRIPTS_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/logout.html" > LOGOUT_HTML_BLOB
           echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/test.txt?$SAS_TOKEN" > TEST_TXT_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/index.html?$SAS_TOKEN" > INDEX_HTML_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/main.js?$SAS_TOKEN" > MAIN_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/polyfills.js?$SAS_TOKEN" > POLYFILLS_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/polyfills-es5.js?$SAS_TOKEN" > POLYFILLS_ES5_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/styles.css?$SAS_TOKEN" > STYLES_CSS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/scripts.js?$SAS_TOKEN" > SCRIPTS_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/logout.html?$SAS_TOKEN" > LOGOUT_HTML_FILE
           echo "hello world" > EXPECTED_TEST_TXT
+          echo "<h1>Hello index.html</h1>" > EXPECTED_STABLE_INDEX_HTML
+          echo "console.log('Hello main.js');" > EXPECTED_STABLE_MAIN_JS
+          echo "console.log('Hello polyfills.js');" > EXPECTED_STABLE_POLYFILLS_JS
+          echo "console.log('Hello polyfills-es5.js');" > EXPECTED_STABLE_POLYFILLS_ES5_JS
+          echo ".helloStyles {}" > EXPECTED_STABLE_STYLES_CSS
+          echo "console.log('Hello scripts.js');" > EXPECTED_STABLE_SCRIPTS_JS
+          echo "<h1>Hello logout.html</h1>" > EXPECTED_STABLE_LOGOUT_HTML
 
       - name: Use storage deploy action
         uses: ./
@@ -55,6 +76,67 @@ jobs:
         run: |
           receivedTestTxt=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat TEST_TXT_FILE)")
           if [[ $receivedTestTxt != $(cat EXPECTED_TEST_TXT) ]] ; then
+            echo "::error ::Deployment has not been successful"
+            exit 1
+          fi
+      
+      - name: Extract branch name
+        shell: bash
+        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
+        id: extract-branch
+      
+      - name: Use storage deploy action with versioning
+        uses: ./
+        with:
+          source-directory: test
+          container: storage-deploy-action-public
+          environment: test
+          region: westeurope
+          version-deployment: true
+          app-name: test-microfrontend
+          branch-name: ${{ steps.extract-branch.outputs.branch }}
+        id: versioned-deployment
+      
+      - name: Versioned deployment to Azure Blob storage has been successful
+        run: |
+          echo ${{ steps.versioned-deployment.outputs.version }} > VERSION
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/index_$(cat VERSION).html" > VERSIONED_INDEX_HTML_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/main_$(cat VERSION).js" > VERSIONED_MAIN_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/polyfills_$(cat VERSION).js" > VERSIONED_POLYFILLS_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/polyfills-es5_$(cat VERSION).js" > VERSIONED_POLYFILLS_ES5_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/styles_$(cat VERSION).css" > VERSIONED_STYLES_CSS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/scripts_$(cat VERSION).js" > VERSIONED_SCRIPTS_JS_BLOB
+          echo "https://leanixwesteuropetest.blob.core.windows.net/storage-deploy-action-public/logout_$(cat VERSION).html" > VERSIONED_LOGOUT_HTML_BLOB
+          receivedVersionedIndexHtml=$(curl -s $(cat VERSIONED_INDEX_HTML_BLOB))
+          receivedVersionedMainJs=$(curl -s $(cat VERSIONED_MAIN_JS_BLOB))
+          receivedVersionedPolyfillsJs=$(curl -s $(cat VERSIONED_POLYFILLS_JS_BLOB))
+          receivedVersionedPolyfillsEs5Js=$(curl -s $(cat VERSIONED_POLYFILLS_ES5_JS_BLOB))
+          receivedVersionedStylesCss=$(curl -s $(cat VERSIONED_STYLES_CSS_BLOB))
+          receivedVersionedScriptsJs=$(curl -s $(cat VERSIONED_SCRIPTS_JS_BLOB))
+          receivedVersionedLogoutHtml=$(curl -s $(cat VERSIONED_LOGOUT_HTML_BLOB))
+          if [[ $receivedVersionedIndexHtml != $(cat EXPECTED_STABLE_INDEX_HTML) || $receivedVersionedMainJs != $(cat EXPECTED_STABLE_MAIN_JS) || $receivedVersionedPolyfillsJs != $(cat EXPECTED_STABLE_POLYFILLS_JS) || $receivedVersionedPolyfillsEs5Js != $(cat EXPECTED_STABLE_POLYFILLS_ES5_JS) || $receivedVersionedStylesCss != $(cat EXPECTED_STABLE_STYLES_CSS) || $receivedVersionedScriptsJs != $(cat EXPECTED_STABLE_SCRIPTS_JS) || $receivedVersionedLogoutHtml != $(cat EXPECTED_STABLE_LOGOUT_HTML) ]] ; then
+            echo "::error ::Versioned Deployment has not been successful"
+            exit 1
+          fi
+
+      - name: Versioned deployment to Azure File Share has been successful
+        run: |
+          echo ${{ steps.versioned-deployment.outputs.version }} > VERSION
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/index_$(cat VERSION).html?$SAS_TOKEN" > VERSIONED_INDEX_HTML_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/main_$(cat VERSION).js?$SAS_TOKEN" > VERSIONED_MAIN_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/polyfills_$(cat VERSION).js?$SAS_TOKEN" > VERSIONED_POLYFILLS_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/polyfills-es5_$(cat VERSION).js?$SAS_TOKEN" > VERSIONED_POLYFILLS_ES5_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/styles_$(cat VERSION).css?$SAS_TOKEN" > VERSIONED_STYLES_CSS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/scripts_$(cat VERSION).js?$SAS_TOKEN" > VERSIONED_SCRIPTS_JS_FILE
+          echo "https://leanixwesteuropetest.file.core.windows.net/k8s-cdn-proxy/storage-deploy-action-public/logout_$(cat VERSION).html?$SAS_TOKEN" > VERSIONED_LOGOUT_HTML_FILE 
+          receivedVersionedIndexHtml=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_INDEX_HTML_FILE)")
+          receivedVersionedMainJs=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_MAIN_JS_FILE)")
+          receivedVersionedPolyfillsJs=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_POLYFILLS_JS_FILE)")
+          receivedVersionedPolyfillsEs5Js=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_POLYFILLS_ES5_JS_FILE)")
+          receivedVersionedStylesCss=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_STYLES_CSS_FILE)")
+          receivedVersionedScriptsJs=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_SCRIPTS_JS_FILE)")
+          receivedVersionedLogoutHtml=$(curl -X GET -H "x-ms-date: $(date -u)" "$(cat VERSIONED_LOGOUT_HTML_FILE)")
+          if [[ $receivedVersionedIndexHtml != $(cat EXPECTED_STABLE_INDEX_HTML) || $receivedVersionedMainJs != $(cat EXPECTED_STABLE_MAIN_JS) || $receivedVersionedPolyfillsJs != $(cat EXPECTED_STABLE_POLYFILLS_JS) || $receivedVersionedPolyfillsEs5Js != $(cat EXPECTED_STABLE_POLYFILLS_ES5_JS) || $receivedVersionedStylesCss != $(cat EXPECTED_STABLE_STYLES_CSS) || $receivedVersionedScriptsJs != $(cat EXPECTED_STABLE_SCRIPTS_JS) || $receivedVersionedLogoutHtml != $(cat EXPECTED_STABLE_LOGOUT_HTML) ]] ; then
             echo "::error ::Deployment has not been successful"
             exit 1
           fi
